<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">
  <xacro:property name="PI" value="3.14159265359" />


  <xacro:property name="chair_width" value="0.6096" /> <!-- 24 inches-->
  <xacro:property name="chair_length" value="0.8382" /> <!-- 33 inches -->
  <xacro:property name="chair_height" value="1.012" /> <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_weight" value="130" />

  <xacro:property name="main_wheel_length" value="0.062" />
  <xacro:property name="main_wheel_radius" value=".1651" /> <!-- 13 inches-->
  <xacro:property name="main_wheel_weight" value="2.0" />

  <xacro:property name="small_wheel_radius" value=".089" /> <!-- 7 inches-->
  <xacro:property name="small_wheel_length" value=".055" />
  <xacro:property name="small_wheel_weight" value="1.0" />

  <xacro:macro name="box_intertia" params="height length width weight" >
    <inertia ixx="${1/12 * weight * (height + length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (width + length)}" iyz="0" izz="${1/12 * weight * (width + height)}" />
  </xacro:macro>

  <xacro:macro name="cylinder_intertia" params="length radius weight" >
    <inertia ixx="${1/12 * weight * (3 * radius * radius + length * length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (3 * radius*radius + length*length)}" iyz="0" izz="${1/2 * weight * radius*radius}" />
  </xacro:macro>


  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chair_height/2 + small_wheel_radius}" rpy="0 0 0" />
      <geometry>
        <box size="${chair_length} ${chair_width} ${chair_height} "/>
      </geometry>
      <material name="white">
        <color rgba="0 0.4 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_length} ${chair_width} ${chair_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chair_weight}"/>
      <xacro:box_intertia height="${chair_height}" length="${chair_length}" width="${chair_width}" weight="${chair_weight}" />
    </inertial>
  </link>


<!--Main Wheels -->

  <joint name="right_main_wheel_joint" type="continuous">
    <axis xyz="0 0 -1"/>
    <parent link="base_link"/>
    <child link="right_main_wheel"/>
    <origin rpy="0 0 0" xyz="0.0 ${chair_width/2 + main_wheel_length/2} ${main_wheel_radius + 0.02}"/> 
  </joint>

  <link name="right_main_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/main_wheel.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>

  <joint name="left_main_wheel_joint" type="continuous">
    <axis xyz="0 0 -1"/>
    <parent link="base_link"/>
    <child link="left_main_wheel"/>
    <origin rpy="0 0 0" xyz="0.0 -${chair_width/2 + main_wheel_length/2} ${main_wheel_radius + 0.02}"/>
  </joint>

  <link name="left_main_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/main_wheel.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>


<!--Front Wheels -->
  <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin rpy="0  0 0" xyz="${chair_length/2} ${chair_width/2 + small_wheel_length/2} ${small_wheel_radius + 0.025}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/caster_wheels.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

  <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin rpy="0 0 0" xyz="${chair_length/2} -${chair_width/2 + small_wheel_length/2} ${small_wheel_radius + 0.025}"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/caster_wheels.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>
<!--Rear Wheels -->


  <joint name="rear_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin rpy="0 0 0" xyz="-${chair_length/2} ${chair_width/2 - small_wheel_length/2} ${small_wheel_radius + 0.025}"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/caster_wheels.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

  <joint name="rear_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin rpy="0 0 0" xyz="-${chair_length/2} -${chair_width/2 - small_wheel_length/2} ${small_wheel_radius + 0.025}"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <mesh filename="package://awl_description/meshes/caster_wheels.dae" scale="1 1 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>
</robot>
